apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: machine
  labels:
    app: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django
        image: anmmoinuddin/myapp:v1 
        ports:
        - containerPort: 8000
---